# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller_commands.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import empower.vbspp.messages.mac_primitives_pb2 as mac__primitives__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='controller_commands.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x19\x63ontroller_commands.proto\x12\x08protocol\x1a\x14mac_primitives.proto\"\xab\x01\n\x0bprp_dl_data\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12$\n\x06\x64l_dci\x18\x02 \x01(\x0b\x32\x14.protocol.prp_dl_dci\x12\x11\n\tce_bitmap\x18\x03 \x03(\r\x12&\n\x07rlc_pdu\x18\x04 \x03(\x0b\x32\x15.protocol.prp_rlc_pdu\x12\x17\n\x0fserv_cell_index\x18\x05 \x01(\r\x12\x14\n\x0c\x61\x63t_deact_ce\x18\x06 \x01(\r\"g\n\nprp_dl_rar\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\r\n\x05grant\x18\x02 \x01(\r\x12%\n\x07rar_dci\x18\x03 \x01(\x0b\x32\x14.protocol.prp_dl_dci\x12\x15\n\rcarrier_index\x18\x04 \x01(\r\"o\n\x10prp_dl_broadcast\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r\x12\'\n\tbroad_dci\x18\x03 \x01(\x0b\x32\x14.protocol.prp_dl_dci\x12\x15\n\rcarrier_index\x18\x04 \x01(\r\"Q\n\x18prp_pdcch_ofdm_sym_count\x12\x15\n\rcarrier_index\x18\x01 \x01(\r\x12\x1e\n\x16num_pdcch_ofdm_symbols\x18\x02 \x01(\r*2\n\x12prp_broadcast_type\x12\r\n\tPRBT_BCCH\x10\x00\x12\r\n\tPRBT_PCCH\x10\x01')
  ,
  dependencies=[mac__primitives__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PRP_BROADCAST_TYPE = _descriptor.EnumDescriptor(
  name='prp_broadcast_type',
  full_name='protocol.prp_broadcast_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRBT_BCCH', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRBT_PCCH', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=536,
  serialized_end=586,
)
_sym_db.RegisterEnumDescriptor(_PRP_BROADCAST_TYPE)

prp_broadcast_type = enum_type_wrapper.EnumTypeWrapper(_PRP_BROADCAST_TYPE)
PRBT_BCCH = 0
PRBT_PCCH = 1



_PRP_DL_DATA = _descriptor.Descriptor(
  name='prp_dl_data',
  full_name='protocol.prp_dl_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rnti', full_name='protocol.prp_dl_data.rnti', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dl_dci', full_name='protocol.prp_dl_data.dl_dci', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ce_bitmap', full_name='protocol.prp_dl_data.ce_bitmap', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rlc_pdu', full_name='protocol.prp_dl_data.rlc_pdu', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serv_cell_index', full_name='protocol.prp_dl_data.serv_cell_index', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='act_deact_ce', full_name='protocol.prp_dl_data.act_deact_ce', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=233,
)


_PRP_DL_RAR = _descriptor.Descriptor(
  name='prp_dl_rar',
  full_name='protocol.prp_dl_rar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rnti', full_name='protocol.prp_dl_rar.rnti', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grant', full_name='protocol.prp_dl_rar.grant', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rar_dci', full_name='protocol.prp_dl_rar.rar_dci', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='carrier_index', full_name='protocol.prp_dl_rar.carrier_index', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=338,
)


_PRP_DL_BROADCAST = _descriptor.Descriptor(
  name='prp_dl_broadcast',
  full_name='protocol.prp_dl_broadcast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='protocol.prp_dl_broadcast.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='protocol.prp_dl_broadcast.index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='broad_dci', full_name='protocol.prp_dl_broadcast.broad_dci', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='carrier_index', full_name='protocol.prp_dl_broadcast.carrier_index', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=451,
)


_PRP_PDCCH_OFDM_SYM_COUNT = _descriptor.Descriptor(
  name='prp_pdcch_ofdm_sym_count',
  full_name='protocol.prp_pdcch_ofdm_sym_count',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='carrier_index', full_name='protocol.prp_pdcch_ofdm_sym_count.carrier_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_pdcch_ofdm_symbols', full_name='protocol.prp_pdcch_ofdm_sym_count.num_pdcch_ofdm_symbols', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=534,
)

_PRP_DL_DATA.fields_by_name['dl_dci'].message_type = mac__primitives__pb2._PRP_DL_DCI
_PRP_DL_DATA.fields_by_name['rlc_pdu'].message_type = mac__primitives__pb2._PRP_RLC_PDU
_PRP_DL_RAR.fields_by_name['rar_dci'].message_type = mac__primitives__pb2._PRP_DL_DCI
_PRP_DL_BROADCAST.fields_by_name['broad_dci'].message_type = mac__primitives__pb2._PRP_DL_DCI
DESCRIPTOR.message_types_by_name['prp_dl_data'] = _PRP_DL_DATA
DESCRIPTOR.message_types_by_name['prp_dl_rar'] = _PRP_DL_RAR
DESCRIPTOR.message_types_by_name['prp_dl_broadcast'] = _PRP_DL_BROADCAST
DESCRIPTOR.message_types_by_name['prp_pdcch_ofdm_sym_count'] = _PRP_PDCCH_OFDM_SYM_COUNT
DESCRIPTOR.enum_types_by_name['prp_broadcast_type'] = _PRP_BROADCAST_TYPE

prp_dl_data = _reflection.GeneratedProtocolMessageType('prp_dl_data', (_message.Message,), dict(
  DESCRIPTOR = _PRP_DL_DATA,
  __module__ = 'controller_commands_pb2'
  # @@protoc_insertion_point(class_scope:protocol.prp_dl_data)
  ))
_sym_db.RegisterMessage(prp_dl_data)

prp_dl_rar = _reflection.GeneratedProtocolMessageType('prp_dl_rar', (_message.Message,), dict(
  DESCRIPTOR = _PRP_DL_RAR,
  __module__ = 'controller_commands_pb2'
  # @@protoc_insertion_point(class_scope:protocol.prp_dl_rar)
  ))
_sym_db.RegisterMessage(prp_dl_rar)

prp_dl_broadcast = _reflection.GeneratedProtocolMessageType('prp_dl_broadcast', (_message.Message,), dict(
  DESCRIPTOR = _PRP_DL_BROADCAST,
  __module__ = 'controller_commands_pb2'
  # @@protoc_insertion_point(class_scope:protocol.prp_dl_broadcast)
  ))
_sym_db.RegisterMessage(prp_dl_broadcast)

prp_pdcch_ofdm_sym_count = _reflection.GeneratedProtocolMessageType('prp_pdcch_ofdm_sym_count', (_message.Message,), dict(
  DESCRIPTOR = _PRP_PDCCH_OFDM_SYM_COUNT,
  __module__ = 'controller_commands_pb2'
  # @@protoc_insertion_point(class_scope:protocol.prp_pdcch_ofdm_sym_count)
  ))
_sym_db.RegisterMessage(prp_pdcch_ofdm_sym_count)


# @@protoc_insertion_point(module_scope)
