# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='header.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x0cheader.proto\x12\x08protocol\"E\n\nprp_header\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x0b\n\x03xid\x18\x04 \x01(\r\x12\x0b\n\x03\x65id\x18\x05 \x01(\r*\xce\x03\n\x08prp_type\x12\x0e\n\nPRPT_HELLO\x10\x00\x12\x15\n\x11PRPT_ECHO_REQUEST\x10\x01\x12\x13\n\x0fPRPT_ECHO_REPLY\x10\x02\x12\x16\n\x12PRPT_STATS_REQUEST\x10\x03\x12\x14\n\x10PRPT_STATS_REPLY\x10\x04\x12\x13\n\x0fPRPT_SF_TRIGGER\x10\x05\x12\x13\n\x0fPRPT_UL_SR_INFO\x10\x06\x12\x1f\n\x1bPRPT_GET_ENB_CONFIG_REQUEST\x10\x07\x12\x1d\n\x19PRPT_GET_ENB_CONFIG_REPLY\x10\x08\x12\x1e\n\x1aPRPT_GET_UE_CONFIG_REQUEST\x10\t\x12\x1c\n\x18PRPT_GET_UE_CONFIG_REPLY\x10\n\x12\x1e\n\x1aPRPT_GET_LC_CONFIG_REQUEST\x10\x0b\x12\x1c\n\x18PRPT_GET_LC_CONFIG_REPLY\x10\x0c\x12\x16\n\x12PRPT_DL_MAC_CONFIG\x10\r\x12\x18\n\x14PRPT_UE_STATE_CHANGE\x10\x0e\x12\x19\n\x15PRPT_DELEGATE_CONTROL\x10\x0f\x12%\n!PRPT_SEND_RRC_MEASUREMENTS_REPORT\x10\x10')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PRP_TYPE = _descriptor.EnumDescriptor(
  name='prp_type',
  full_name='protocol.prp_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRPT_HELLO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_ECHO_REQUEST', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_ECHO_REPLY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_STATS_REQUEST', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_STATS_REPLY', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_SF_TRIGGER', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_UL_SR_INFO', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_GET_ENB_CONFIG_REQUEST', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_GET_ENB_CONFIG_REPLY', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_GET_UE_CONFIG_REQUEST', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_GET_UE_CONFIG_REPLY', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_GET_LC_CONFIG_REQUEST', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_GET_LC_CONFIG_REPLY', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_DL_MAC_CONFIG', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_UE_STATE_CHANGE', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_DELEGATE_CONTROL', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRPT_SEND_RRC_MEASUREMENTS_REPORT', index=16, number=16,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=98,
  serialized_end=560,
)
_sym_db.RegisterEnumDescriptor(_PRP_TYPE)

prp_type = enum_type_wrapper.EnumTypeWrapper(_PRP_TYPE)
PRPT_HELLO = 0
PRPT_ECHO_REQUEST = 1
PRPT_ECHO_REPLY = 2
PRPT_STATS_REQUEST = 3
PRPT_STATS_REPLY = 4
PRPT_SF_TRIGGER = 5
PRPT_UL_SR_INFO = 6
PRPT_GET_ENB_CONFIG_REQUEST = 7
PRPT_GET_ENB_CONFIG_REPLY = 8
PRPT_GET_UE_CONFIG_REQUEST = 9
PRPT_GET_UE_CONFIG_REPLY = 10
PRPT_GET_LC_CONFIG_REQUEST = 11
PRPT_GET_LC_CONFIG_REPLY = 12
PRPT_DL_MAC_CONFIG = 13
PRPT_UE_STATE_CHANGE = 14
PRPT_DELEGATE_CONTROL = 15
PRPT_SEND_RRC_MEASUREMENTS_REPORT = 16



_PRP_HEADER = _descriptor.Descriptor(
  name='prp_header',
  full_name='protocol.prp_header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='protocol.prp_header.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='protocol.prp_header.type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xid', full_name='protocol.prp_header.xid', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eid', full_name='protocol.prp_header.eid', index=3,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['prp_header'] = _PRP_HEADER
DESCRIPTOR.enum_types_by_name['prp_type'] = _PRP_TYPE

prp_header = _reflection.GeneratedProtocolMessageType('prp_header', (_message.Message,), dict(
  DESCRIPTOR = _PRP_HEADER,
  __module__ = 'header_pb2'
  # @@protoc_insertion_point(class_scope:protocol.prp_header)
  ))
_sym_db.RegisterMessage(prp_header)


# @@protoc_insertion_point(module_scope)
