version: "3.7"

services:

  runtime:
    network_mode: host
    image: winlab/empower-runtime
    depends_on:
      - mongo
      - influxdb
      - grafana

  influxdb:
    network_mode: host
    image: influxdb
    volumes:
      - ~/Docker/influxdb:/var/lib/influxdb

  mongo:
    network_mode: host
    image: mongo
    volumes:
      - ~/Docker/mongodb:/data/db

  grafana:
    network_mode: host
    image: grafana/grafana
    volumes:
      - ~/Docker/grafana:/var/lib/grafana
    depends_on:
      - influxdb
