# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0bhello.proto\"\x17\n\x05hello\x12\x0e\n\x06period\x18\x01 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HELLO = _descriptor.Descriptor(
  name='hello',
  full_name='hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='period', full_name='hello.period', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=38,
)

DESCRIPTOR.message_types_by_name['hello'] = _HELLO

hello = _reflection.GeneratedProtocolMessageType('hello', (_message.Message,), dict(
  DESCRIPTOR = _HELLO,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello)
  ))
_sym_db.RegisterMessage(hello)


# @@protoc_insertion_point(module_scope)
