# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import empower.vbsp.messages.hello_pb2 as hello__pb2
import empower.vbsp.messages.statistics_pb2 as statistics__pb2
import empower.vbsp.messages.configs_pb2 as configs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='main.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\nmain.proto\x1a\x0bhello.proto\x1a\x10statistics.proto\x1a\rconfigs.proto\"e\n\x06header\x12\x16\n\x04type\x18\x01 \x01(\x0e\x32\x08.MsgType\x12\x0c\n\x04vers\x18\x02 \x01(\r\x12\x0c\n\x04\x62_id\x18\x03 \x01(\r\x12\x0c\n\x04m_id\x18\x04 \x01(\r\x12\x0b\n\x03seq\x18\x05 \x01(\r\x12\x0c\n\x04t_id\x18\x06 \x01(\r\"\x82\x01\n\temage_msg\x12\x15\n\x04head\x18\x01 \x01(\x0b\x32\x07.header\x12\x18\n\x06mHello\x18\x02 \x01(\x0b\x32\x06.helloH\x00\x12\x1d\n\x06mStats\x18\x03 \x01(\x0b\x32\x0b.statisticsH\x00\x12\x1a\n\x06mConfs\x18\x04 \x01(\x0b\x32\x08.configsH\x00\x42\t\n\x07message*n\n\x07MsgType\x12\x0b\n\x07INVALID\x10\x00\x12\r\n\tHELLO_REQ\x10\x01\x12\r\n\tHELLO_REP\x10\x02\x12\r\n\tSTATS_REQ\x10\x03\x12\r\n\tSTATS_REP\x10\x04\x12\x0c\n\x08\x43ONF_REQ\x10\x05\x12\x0c\n\x08\x43ONF_REP\x10\x06')
  ,
  dependencies=[hello__pb2.DESCRIPTOR,statistics__pb2.DESCRIPTOR,configs__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MSGTYPE = _descriptor.EnumDescriptor(
  name='MsgType',
  full_name='MsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HELLO_REQ', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HELLO_REP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATS_REQ', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATS_REP', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONF_REQ', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONF_REP', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=296,
  serialized_end=406,
)
_sym_db.RegisterEnumDescriptor(_MSGTYPE)

MsgType = enum_type_wrapper.EnumTypeWrapper(_MSGTYPE)
INVALID = 0
HELLO_REQ = 1
HELLO_REP = 2
STATS_REQ = 3
STATS_REP = 4
CONF_REQ = 5
CONF_REP = 6



_HEADER = _descriptor.Descriptor(
  name='header',
  full_name='header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='header.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vers', full_name='header.vers', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b_id', full_name='header.b_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_id', full_name='header.m_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='header.seq', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='t_id', full_name='header.t_id', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=161,
)


_EMAGE_MSG = _descriptor.Descriptor(
  name='emage_msg',
  full_name='emage_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='head', full_name='emage_msg.head', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mHello', full_name='emage_msg.mHello', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mStats', full_name='emage_msg.mStats', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mConfs', full_name='emage_msg.mConfs', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='emage_msg.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=164,
  serialized_end=294,
)

_HEADER.fields_by_name['type'].enum_type = _MSGTYPE
_EMAGE_MSG.fields_by_name['head'].message_type = _HEADER
_EMAGE_MSG.fields_by_name['mHello'].message_type = hello__pb2._HELLO
_EMAGE_MSG.fields_by_name['mStats'].message_type = statistics__pb2._STATISTICS
_EMAGE_MSG.fields_by_name['mConfs'].message_type = configs__pb2._CONFIGS
_EMAGE_MSG.oneofs_by_name['message'].fields.append(
  _EMAGE_MSG.fields_by_name['mHello'])
_EMAGE_MSG.fields_by_name['mHello'].containing_oneof = _EMAGE_MSG.oneofs_by_name['message']
_EMAGE_MSG.oneofs_by_name['message'].fields.append(
  _EMAGE_MSG.fields_by_name['mStats'])
_EMAGE_MSG.fields_by_name['mStats'].containing_oneof = _EMAGE_MSG.oneofs_by_name['message']
_EMAGE_MSG.oneofs_by_name['message'].fields.append(
  _EMAGE_MSG.fields_by_name['mConfs'])
_EMAGE_MSG.fields_by_name['mConfs'].containing_oneof = _EMAGE_MSG.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['header'] = _HEADER
DESCRIPTOR.message_types_by_name['emage_msg'] = _EMAGE_MSG
DESCRIPTOR.enum_types_by_name['MsgType'] = _MSGTYPE

header = _reflection.GeneratedProtocolMessageType('header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'main_pb2'
  # @@protoc_insertion_point(class_scope:header)
  ))
_sym_db.RegisterMessage(header)

emage_msg = _reflection.GeneratedProtocolMessageType('emage_msg', (_message.Message,), dict(
  DESCRIPTOR = _EMAGE_MSG,
  __module__ = 'main_pb2'
  # @@protoc_insertion_point(class_scope:emage_msg)
  ))
_sym_db.RegisterMessage(emage_msg)


# @@protoc_insertion_point(module_scope)
